### ISSUE TITLE
Broken Pipes cause DR process to crash

### ISSUE THREAD

**Issue by JamJar00** [DarkRiftNetworking/DarkRift#126]
### Quick Description
When a client disconnects with a broken pipe the DarkRift an ObjectDisposedException is thrown and the DarkRift process exits (for some reason).

### Explanation
The following exception is often thrown when a client disconnects with a broken pipe:
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   at DarkRift.Server.Plugins.Listeners.Bichannel.BichannelServerConnection.ReceiveHeaderAndBody(SocketAsyncEventArgs args) in P:\Git\dr2-custom\DarkRift.Server\Plugins\Listeners\Bichannel\BichannelServerConnection.cs:line 240
   at DarkRift.Server.Plugins.Listeners.Bichannel.BichannelServerConnection.AsyncReceiveHeaderCompleted(Object sender, SocketAsyncEventArgs args) in P:\Git\dr2-custom\DarkRift.Server\Plugins\Listeners\Bichannel\BichannelServerConnection.cs:line 277
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

- DarkRift standalone running inside a Docker container (in portainer)
- BichannelListener

While I'm not convinced the process exiting is because of the exception on the thread pool thread, I think DarkRift should catch ObjectDisposedExceptions from the socket and handle them gracefully regardless.

Additionally, why is the broken pipe not triggering the disconnection guards on the header receive? Is there a condition missing?

**Comment by gitMM** [comment]
I think I'm having the same issue. Seems like UDP just stops work in a bichannel listener on a broken pipe client and TCP continues. There's no error or exception.
