### ISSUE TITLE
Critical Error during TCP Packet Receive

### ISSUE THREAD

**Issue by tjdqudqls** [DarkRiftNetworking/DarkRift#90]
Under Pressure, DR2 2.4.5 gives errors quite often while receiving packets.
This is the error.
```
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: count
   at System.Net.Sockets.SocketAsyncEventArgs.SetBuffer(Byte[] buffer, Int32 offset, Int32 count)
   at DarkRift.Server.Plugins.Listeners.Bichannel.BichannelServerConnection.TcpHeaderReceiveCompleted(Object sender, SocketAsyncEventArgs e)
   at DarkRift.Server.Plugins.Listeners.Bichannel.BichannelServerConnection.TcpBodyReceiveCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

We have currently fixed it by comparing 2.3.5 version of BichannelServerConnection.cs. (Seems to have been fixed for now, we are monitoring.)

Our team thinks that It is due to the autorecyclingArray class used in DR2  probably related to thread issues since dr2 is making a lot of thread during runtime.

We also encountered this which could be the problem but needs more inspection to it.
[](https://social.msdn.microsoft.com/Forums/en-US/40fe397c-b1da-428e-a355-ee5a6b0b4d2c/socketasynceventargssetbuffer-bug-?forum=ncl
)

**Comment by JamJar00** [comment]
Hi tjdqudqls,

This is certainly an interesting error. Can you elaborate as to whether you're running the .NET Standard version or the .NET Framework version of DarkRift? I've notice some very major differences in .NET's implementation of the APIs used here between the two platforms which might help narrow the issue down, if you can try the other that would be even more helpful!

I've recently refactored a lot of this class in order to fix a bug when running in .NET Standard so I'll try and get an early build of that to you to test as well!

Many Thanks,

Jamie

**Comment by tjdqudqls** [comment]
> Hi tjdqudqls,
> 
> This is certainly an interesting error. Can you elaborate as to whether you're running the .NET Standard version or the .NET Framework version of DarkRift? I've notice some very major differences in .NET's implementation of the APIs used here between the two platforms which might help narrow the issue down, if you can try the other that would be even more helpful!
> 
> I've recently refactored a lot of this class in order to fix a bug when running in .NET Standard so I'll try and get an early build of that to you to test as well!
> 
> Many Thanks,
> 
> Jamie

It happened on our standalone server so we were using the .Net standard version.
 :)thank you!!

**Comment by tjdqudqls** [comment]
> Application: dotnet.exe
> CoreCLR Version: 4.6.26919.2
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'System.Net.Sockets.Socket'.
>    at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
>    at DarkRift.Server.Plugins.Listeners.Bichannel.BichannelServerConnection.TcpHeaderReceiveCompleted(Object sender, SocketAsyncEventArgs e)
>    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
>    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
>    at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__177_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
>    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

new error just came up from our server ;_; just sharing because might be related

**Comment by JamJar00** [comment]
On the Discord it was mentioned this issue occurrs on Android.
